// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpS3sf8JaL2dyDzC8tEYmm98TFDBJh2qI',
    appId: '1:1058306392151:web:1462d4a87322ad96fe2312',
    messagingSenderId: '1058306392151',
    projectId: 'inappmessaging-bd6d6',
    authDomain: 'inappmessaging-bd6d6.firebaseapp.com',
    databaseURL: 'https://inappmessaging-bd6d6-default-rtdb.firebaseio.com',
    storageBucket: 'inappmessaging-bd6d6.appspot.com',
    measurementId: 'G-R5MWV9ZENL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUe2CPY2A_-zq-Vs7HpZ_kyKdNq28rHRA',
    appId: '1:1058306392151:android:940433e450b70977fe2312',
    messagingSenderId: '1058306392151',
    projectId: 'inappmessaging-bd6d6',
    databaseURL: 'https://inappmessaging-bd6d6-default-rtdb.firebaseio.com',
    storageBucket: 'inappmessaging-bd6d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFir7QOQ0SnM4UwSNUnVSrfN7T8JlmflY',
    appId: '1:1058306392151:ios:c12d138cc9ecc210fe2312',
    messagingSenderId: '1058306392151',
    projectId: 'inappmessaging-bd6d6',
    databaseURL: 'https://inappmessaging-bd6d6-default-rtdb.firebaseio.com',
    storageBucket: 'inappmessaging-bd6d6.appspot.com',
    iosBundleId: 'com.example.flutterNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFir7QOQ0SnM4UwSNUnVSrfN7T8JlmflY',
    appId: '1:1058306392151:ios:7694536334b77114fe2312',
    messagingSenderId: '1058306392151',
    projectId: 'inappmessaging-bd6d6',
    databaseURL: 'https://inappmessaging-bd6d6-default-rtdb.firebaseio.com',
    storageBucket: 'inappmessaging-bd6d6.appspot.com',
    iosBundleId: 'com.example.flutterNotification.RunnerTests',
  );
}
